### PR TITLE
Challenges Page

### PR DESCRIPTION
**Pull request by jujg99**
## Issues addressed:
#32

### CODE REVIEW

**Comment by dhruvilp** [comment]
@jujg99 this is great so far! I think it would be better to add TabsView (https://demos.creative-tim.com/argon-design-system-react/#/documentation/navs) for switching between datasets & models download as I told you earlier, and try to add simple text file download. We'll merge into `master` right after.

**Comment by jujg99** [comment]
> @jujg99 this is great so far! I think it would be better to add TabsView (https://demos.creative-tim.com/argon-design-system-react/#/documentation/navs) for switching between datasets & models download as I told you earlier, and try to add simple text file download. We'll merge into `master` right after.

@dhruvilp I was trying to change to TabsView and I went to login from the login page to get to challenges, but an error came up. It was working fine before, do you know how I can fix this?

`Error: Objects are not valid as a React child (found: TypeError: Failed to fetch). If you meant to render a collection of children, use an array instead.
    in div (created by Transition)
    in Transition (created by Fade)
    in Fade (created by Alert)
    in Alert (created by UncontrolledAlert)
    in UncontrolledAlert (at Login.jsx:100)
    in div (at Login.jsx:99)
    in div (created by CardBody)
    in CardBody (at Login.jsx:92)
    in div (created by Card)
    in Card (at Login.jsx:84)
    in div (created by Col)
    in Col (at Login.jsx:83)
    in div (created by Row)
    in Row (at Login.jsx:82)
    in div (created by Container)
    in Container (at Login.jsx:81)
    in section (at Login.jsx:80)
    in main (at Login.jsx:79)
    in Login (at src/index.js:25)
    in Route (at src/index.js:22)
    in Switch (at src/index.js:21)
    in Router (created by BrowserRouter)
    in BrowserRouter (at src/index.js:20)
    in StrictMode (at src/index.js:19)`

**Comment by dhruvilp** [comment]
@jujg99  I didn't change anything in Login.jsx file. Did you start MondoDB client and backend server locally? Before login?

**Comment by dhruvilp** [comment]
@jujg99 does it work now? also try creating a new user and then try login

**Comment by jujg99** [comment]
@dhruvilp i actually didn't start MongoDB or backend server before and it was working, but I'm trying it out now

**Comment by dhruvilp** [comment]
@jujg99 it was working because login wasn't implemented  back then and your branch wasn't up-to-date with current master branch so that's why it was working!

To run mongodb: (terminal tab 1)
`mongod`
To run backend: (terminal tab 2)
`pip install -r requirements.txt`
`python3 app.py`

Then run reactJs app:
`npm install`
`npm start`

**Comment by jujg99** [comment]
@dhruvilp I'm not sure how mongodb works, I've created an account on mongodb and downloaded mongodb, but I'm not sure where to go from here. Thank you so much for helping me

**Comment by dhruvilp** [comment]
@jujg99 Actually, you don't need mongodb account. Just run `pip install -r requirements.txt` and it'll install mongodb client library in your python flask environment (look backend readme file for how to activate virtual ENV) and then you're good to go!

**Comment by jujg99** [comment]
@dhruvilp okay I'll try it out right now, thank you!

**Pull request merged**
