### PR TITLE
Update UserDashboard.jsx

### PR DESCRIPTION
**Pull request by jujg99**
@dhruvilp I'm not sure if I did this correctly, is the uploaded models list supposed to be empty initially until the user actually uploads something? Or should it start with those two models in the list?

### CODE REVIEW

**Comment by dhruvilp** [comment]
@jujg99 no, we should only display what each user uploaded. models uploaded by admin should be only displayed in challenges page

**Comment by dhruvilp** [comment]
@jujg99 Hey, I would recommend using same upload file styling as we did in `admin:dashboard`, just to be consistent with overall stylings. Below is the reference for code and you can also look at the Dashboard.jsx file. Also, you can divide `browse file` and and `upload` button in a row so it'll align properly. Great work so far!

I've also added functions to get data from backend which I'm pushing in my next PR
 
Screen Shot 2020-04-26 at 10 44 10 PM

**Comment by jujg99** [comment]
@dhruvilp  okay, I'll fix it right now! And so the uploaded models list should be empty , right?

**Comment by dhruvilp** [comment]
@jujg99 yes! it's nice to have a message saying nothing uploaded yet!

**Pull request merged**
